function(a) {

			ok(false, 'テスト失敗。readyPromiseがresolve()された');

		}