function(context) {

				ok(false, 'テスト失敗。__readyが実行された');

			}