function() {
                    Y.Assert.fail("Example does not seem to have executed within " + TIMEOUT + "ms.");
                }