function (error) {
          assert.instanceOf(error, Error);
        }