function (err)Â {
        callback({err: 'there was an error'}, undefined);
      }